# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BasicDataAugmentation
                                 A QGIS plugin
 This plugin generates data augmentation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-05-15
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Gabriel Koyama
        email                : gabriel.koyama44@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import shutil
# import tensorflow as tf
# import tensorflow_addons as tfa

from random import randint

from osgeo import gdal, osr
from qgis.utils import iface
from qgis.core import QgsProject, Qgis
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog

import numpy as np
from scipy.ndimage import gaussian_filter
from skimage.transform import resize
import cv2

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .basic_data_augmentation_dialog import BasicDataAugmentationDialog
import os.path


class BasicDataAugmentation:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'BasicDataAugmentation_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&basic_data_augmentation')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('BasicDataAugmentation', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/basic_data_augmentation/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Basic Data Augmentation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&basic_data_augmentation'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_output_file(self):
        _dir = QFileDialog.getExistingDirectory(self.dlg, "Select output directory ")
        self.dlg.lineEdit.setText(_dir)

    def readLayer(self, src=None):

        # if src not provided read path selected layer
        if(src == None): 
            self.dataset = gdal.Open( self.selectedLayerPath )
        else:
            self.dataset = gdal.Open( src )

        # Get first band -- considering only one band tif as input
        self.band       = self.dataset.GetRasterBand(1)
        self.bandArr   = self.band.ReadAsArray()

        # Get properties to save later
        self.geoTransform = self.dataset.GetGeoTransform()
        self.projection = self.dataset.GetProjection()

        return self.bandArr.copy()

    def saveLayer(self, dst, arr):

        [rows, cols] = arr.shape

        driver = gdal.GetDriverByName("GTiff")
        outdata = driver.Create(dst, cols, rows, 1, gdal.GDT_UInt16)

        outdata.SetGeoTransform(self.geoTransform)
        outdata.SetProjection(self.projection) 
        outdata.GetRasterBand(1).WriteArray(arr)
        outdata.GetRasterBand(1).SetNoDataValue(10000)

        outdata.FlushCache()

        outdata = None
    
    # Rotação:
    def rotate(self, img, degrees):
        return (np.rot90(img, k=int(degrees / 90)))

    # Espelhamento:
    def flip(self, img, direction):
        if (direction == "vertical"):
            return (img[::-1, ::])
        elif (direction == "horizontal"):
            return (img[::, ::-1])
        elif (direction == "both"):
            return (img[::-1, ::-1])

    # Aparagem:
    def trim(self, img, top=0, bottom=0, left=0, right=0):
        return (img[top:-bottom, right:-left])

    # Recorte:
    def crop(self, img, right=0, top=0, left=100, bottom=100):
        return (img[top:bottom, right:left])

    # Gaussian blur:
    def blur(self, img, sigma=1):
        return(gaussian_filter(img, sigma=sigma))

    # Redimensionamento:
    def rescale(self, img, ratio):
        return (resize(img, (int(img.shape[1] * ratio), int(img.shape[0] * ratio))))

    # Binarização:
    def binary(self, img, threshold=120, inv=False, bw=True):
        if (inv == False):
            method = cv2.THRESH_BINARY
        else:
            method = cv2.THRESH_BINARY_INV

        if (bw == True):
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        return(cv2.threshold(img, threshold, 255, method)[1])

    # Truncagem:
    def trunc(self, img, threshold=120, max=255):
        return (cv2.threshold(img, threshold, max, cv2.THRESH_TRUNC)[1])

    # Extração e realce de bordas:
    def edgy(self, img, threshold=120, max=255, aperture=3, mask=True):
        edges = cv2.Canny(img, threshold, max, aperture)

        if (mask == True):
            return (cv2.bitwise_and(img, img, mask=cv2.bitwise_not(edges)))

        return(edges)
    
    # Rotina de data augmentation:
    def augmentate(self, img, chunks=100, invert=3, rotations=3, blur_sigmas=5):
        res = []
        areas = []

        while (len(areas) != chunks):
            x = randint(0, img.shape[1] - 100)
            y = randint(0, img.shape[0] - 100)
            if ((x, y) not in areas):
                areas.append((x, y))

        for coords in areas:
            nimg = self.crop(img, coords[0], coords[1], coords[0] + 100, coords[1] + 100)

            for x in [nimg, self.flip(nimg, "vertical"), self.flip(nimg, "horizontal"), self.flip(nimg, "both")][:invert + 1]:
                for y in [0, 90, 180, 270][:rotations + 1]:
                    res.append(self.rotate(x, y))
                    for s in range(1, blur_sigmas + 1):
                        res.append(self.rotate(self.blur(x, sigma=s), y))

        return (res)

    def checkBox(self):

        _out = os.path.join(self.outputDir, self.satName)
        root, ext = os.path.splitext(_out) # check ext
        

        # Rotate
        if self.dlg.checkBox.isChecked():
            _out = root + "_ROTATE.tif"
            self.saveLayer(_out, self.rotate(self.bandArr, 90))
            self.layersAdded.append(_out)

        # Flip
        if self.dlg.checkBox_2.isChecked():
            flipOpt = ["vertical", "horizontal", "both"]
            for fo in flipOpt:
                _out = root + f"_{fo.upper()}.tif"
                self.saveLayer(_out, self.flip(self.bandArr, fo))
                self.layersAdded.append(_out)

        # Trim
        if self.dlg.checkBox_3.isChecked():
            _out = root + "_TRIM.tif"
            self.saveLayer(_out, self.trim(self.bandArr, 200, 200, 20, 20))
            self.layersAdded.append(_out)

        # Crop
        if self.dlg.checkBox_4.isChecked():
            _out = root + "_CROP.tif"
            self.saveLayer(_out, self.crop(self.bandArr, 100, 100, 200, 200))
            self.layersAdded.append(_out)

        # Blur
        if self.dlg.checkBox_5.isChecked():
            _out = root + "_BLUR.tif"
            self.saveLayer(_out, self.blur(self.bandArr, sigma=2))
            self.layersAdded.append(_out)
        
        # Rescale
        if self.dlg.checkBox_6.isChecked():
            _out = root + "_RESCALE.tif"
            self.saveLayer(_out, self.rescale(self.bandArr, 0.5))
            self.layersAdded.append(_out)

        # Augmentate
        if self.dlg.checkBox_7.isChecked():

            _outDirAug = os.path.join(self.outputDir, "augmentation")

            # Remove folder
            if(os.path.isdir(_outDirAug)): shutil.rmtree(_outDirAug) 

            os.mkdir(_outDirAug)

            # generates images
            images = self.augmentate(self.bandArr)
            
            self.iface.messageBar().pushMessage( f"Images: {len(images)}", level=Qgis.Info, duration=3)
        
            for idx, image in enumerate(images[:100]):
                name, ext = os.path.splitext(self.satName)
                name = name + "_" + str(idx) + ".tif"
                _outFileAug = os.path.join(_outDirAug, name)
                self.saveLayer(_outFileAug, image)
            


        # Binary
        if self.dlg.checkBox_8.isChecked():
            _out = root + "_BINARY.tif"
            self.saveLayer(_out, self.binary(self.bandArr, bw=False, threshold=50, inv=True))
            self.layersAdded.append(_out)

        # Truncate
        if self.dlg.checkBox_9.isChecked():
            _out = root + "_TRUNC.tif"
            self.saveLayer(_out, self.trunc(self.bandArr, 100, 200))
            self.layersAdded.append(_out)

        # Edgy
        if self.dlg.checkBox_10.isChecked():
            _out = root + "_EDGY.tif"
            self.saveLayer(_out, self.edgy(self.bandArr))
            self.layersAdded.append(_out)
        
    def run(self):

        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = BasicDataAugmentationDialog()

            # On click button select output file
            self.dlg.pushButton.clicked.connect(self.select_output_file)
        
        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()

        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()

        # Populate the comboBox with names of all the loaded layers
        # Check if there is any layers
        if not(len(layers) == 0): self.dlg.comboBox.addItems([layer.name() for layer in layers])

        # show the dialog
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()

        # See if OK was pressed
        if result:

            self.layersAdded        = []
            self.selectedLayerIndex = None
            self.filename           = None
            self.selectedLayer      = None
            self.selectedLayerPath  = None
            self.satName            = None


            # Get selected layer index
            self.selectedLayerIndex = self.dlg.comboBox.currentIndex()

            # Get output path
            self.outputDir  = self.dlg.lineEdit.text()

            # Required fields
            if(len(layers) == 0 or self.outputDir == ""):
                self.iface.messageBar().pushMessage("Error", "Missing output directory", level=Qgis.Critical)
                return

            # Get selected layer
            self.selectedLayer     = layers[self.selectedLayerIndex].layer()
            self.selectedLayerPath = self.selectedLayer.dataProvider().dataSourceUri()
            self.satName           = os.path.split(self.selectedLayerPath)[-1]

            # Get array and info from selected layer
            self.readLayer()

            # check chosen methods
            self.checkBox()

            # plot output layers
            for l in self.layersAdded:
                self.iface.addRasterLayer(l, os.path.split(l)[1])

            # message success
            
            # msg = f"SelectedLayer: {self.selectedLayer.dataProvider().dataSourceUri()}"
            # msg = f"Output: {self.output_dir}"
            # self.iface.messageBar().pushMessage( msg, level=Qgis.Success, duration=5)

            self.iface.messageBar().pushMessage( "Success!", level=Qgis.Success, duration=3)
