# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BasicDataAugmentation
                                 A QGIS plugin
 This plugin generates data augmentation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-05-15
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Gabriel Koyama
        email                : gabriel.koyama44@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

# import tensorflow as tf
# import tensorflow_addons as tfa

from osgeo import gdal, osr
from qgis.utils import iface
from qgis.core import QgsProject, Qgis
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog

import numpy as np

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .basic_data_augmentation_dialog import BasicDataAugmentationDialog
import os.path


class BasicDataAugmentation:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'BasicDataAugmentation_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&basic_data_augmentation')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # My variables
        self.output_dir = "/tmp"
        self.layers_added = []


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('BasicDataAugmentation', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/basic_data_augmentation/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Basic Data Augmentation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&basic_data_augmentation'),
                action)
            self.iface.removeToolBarIcon(action)


    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg, "Select   output file ","",)
        self.dlg.lineEdit.setText(filename)

    # read gdal selected layer
    def readGdal(self,src=None):
        if(src == None): 
            gdal.Open( self.selectedLayerPath )
        else:
            gdal.Open( src )

        self.src_ds     = gdal.Open( self.selectedLayerPath )
        self.dataset    = self.src_ds
        # self.prj        = self.src_ds.GetProjection()
        self.band       = self.src_ds.GetRasterBand(1)
        self.band_arr   = self.band.ReadAsArray()
        return self.band_arr.copy()

    def getNewArr(self):
        arr = self.readGdal()
        arr = np.where(arr>50, 1, 0) # especifico pro CBERS
        return arr # retorna mascara 0 e 1 

    def saveGdalOLDProjectionErr(self, src_filename, dst_filename):
        

        # pegando shape x e y
        selectedLayer = self.readGdal()
        SelectedLayer_shape = selectedLayer.shape

        # setando projecao geografica
        srs = osr.SpatialReference()
        srs.ImportFromEPSG(27700)

        # salvando
        driver = gdal.GetDriverByName('GTiff')
        dst_ds = driver.Create(dst_filename, SelectedLayer_shape[1], SelectedLayer_shape[0])

        # projecao
        dst_ds.SetProjection(self.prj)

        band = dst_ds.GetRasterBand(1)
        arr = band.ReadAsArray()  # raster values are all zero

        # modificando dados
        arr = self.getNewArr()  # modify data

        band.WriteArray(arr)  # raster file still unmodified
        band = None  # dereference band to avoid gotcha described previously
        dst_ds = None  # save, close

    def saveGdalSAFE(self, src_filename, dst_filename):
        ds = gdal.Open(src_filename)
        band = ds.GetRasterBand(1)
        arr = band.ReadAsArray()

        [rows, cols] = arr.shape
        # arr_min = arr.min()
        # arr_max = arr.max()
        # arr_mean = int(arr.mean())
        # arr_out = np.where((arr < arr_mean), 10000, arr)

        arr_out = self.getNewArr()

        driver = gdal.GetDriverByName("GTiff")
        outdata = driver.Create(dst_filename, cols, rows, 1, gdal.GDT_UInt16)

        outdata.SetGeoTransform(ds.GetGeoTransform()) ##sets same geotransform as input
        outdata.SetProjection(ds.GetProjection()) ##sets same projection as input
        outdata.GetRasterBand(1).WriteArray(arr_out)
        outdata.GetRasterBand(1).SetNoDataValue(10000) ##if you want these values transparent

        outdata.FlushCache()

        outdata = None
        band=None
        ds=None
    
    def saveGdal(self, src_filename, dst_filename, arr_out):
        ds = gdal.Open(src_filename)
        # band = ds.GetRasterBand(1)
        # arr = band.ReadAsArray()

        [rows, cols] = arr_out.shape


        driver = gdal.GetDriverByName("GTiff")
        outdata = driver.Create(dst_filename, cols, rows, 1, gdal.GDT_UInt16)
        

        outdata.SetGeoTransform(ds.GetGeoTransform()) ##sets same geotransform as input
        outdata.SetProjection(ds.GetProjection()) ##sets same projection as input
        outdata.GetRasterBand(1).WriteArray(arr_out)
        outdata.GetRasterBand(1).SetNoDataValue(10000) ##if you want these values transparent

        outdata.FlushCache()

        outdata = None
        # band=None
        ds=None
    

    def flip(self):
        flip = dict()
        flip["hor"] = np.flipud(self.band_arr)
        flip["ver"] = np.fliplr(self.band_arr)
        self.output_flip = None

        # salvando os meotdos de flip
        for method in flip:
            # montando nome
            output_name = self.sat_name.split(".")[0] + "_" + method.upper() + "_" + self.sat_name.split(".")[1]
            output_flip = os.path.join(self.output_dir, output_name)

            self.saveGdal(self.selectedLayerPath, output_flip, flip[method])
            self.layers_added.append(output_flip) # guardando em uma variavel para plotar dps
            
        # # ja existe?
        # if(os.path.isdir(self.output)):
        #     os.remove(self.output) # remove

        # Abrir layer na tela
        # self.iface.addRasterLayer(self.output, "teste")


    def rotate(self, type):
        # depois unificar rotate e flip
        rotate = dict()
        if(type == 90):
            rotate["rot90"]  = np.rot90(self.band_arr, k=1, axes=(0,1))
        elif(type == 180):
            rotate["rot180"] = np.rot90(self.band_arr, k=2, axes=(0,1))
        
        self.output_flip = None

        # salvando os meotdos de flip
        for method in rotate:
            # montando nome
            output_name = self.sat_name.split(".")[0] + "_" + method.upper() + "_" + self.sat_name.split(".")[1]
            output_rotate = os.path.join(self.output_dir, output_name)

            self.saveGdal(self.selectedLayerPath, output_rotate, rotate[method])
            self.layers_added.append(output_rotate) # guardando em uma variavel para plotar dps
            

    def checkBox(self):
        # Rotate 90
        if self.dlg.checkBox.isChecked():
            self.options.append("90")
            self.rotate(90)

        # Rotate 180
        if self.dlg.checkBox_2.isChecked():
            self.options.append("180")
            self.rotate(180)

        # Transform
        if self.dlg.checkBox_3.isChecked():
            self.options.append("tranform")
        
        # Mean filter
        if self.dlg.checkBox_4.isChecked():
            self.options.append("filter")

        # Flip
        if self.dlg.checkBox_5.isChecked():
            self.options.append("flip")
            self.flip()

        

    def run(self):

        self.options = []

        # limpar pasta /tmp tudo .tif, .jpeg ...

        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = BasicDataAugmentationDialog()
        

        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()


        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        # Populate the comboBox with names of all the loaded layers
        self.dlg.comboBox.addItems([layer.name() for layer in layers])

        # fazer esta validacao dps tbm
        if not(len(layers) == 0):
            # Selected layer
            self.selectedLayerIndex = self.dlg.comboBox.currentIndex()
            self.selectedLayer = layers[self.selectedLayerIndex].layer()
            self.selectedLayerPath = self.selectedLayer.dataProvider().dataSourceUri()
            self.sat_name = os.path.split(self.selectedLayerPath)[-1]
            self.dlg.pushButton.clicked.connect(self.select_output_file)

            # filename = self.dlg.lineEdit.text()


            # print(f"Layer: {self.selectedLayer.dataProvider().dataSourceUri()}")

            # read image
            self.readGdal()

        # print("Reading selectedLayer")
        # self.dataset = gdal.Open(self.selectedLayer.dataProvider().dataSourceUri(), gdal.GA_ReadOnly)

        # print("Reading as aray")
        # self.img     = self.dataset.GetRasterBand(1).ReadAsArray()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:

            # verifica checkbox
            self.checkBox()

            # plotando mudancas
            for l in self.layers_added:
                name = os.path.split(l)[1]
                self.iface.addRasterLayer(l, name)

            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            self.iface.messageBar().pushMessage(
                f"OPTIONS: {self.options}\n" + 
                f"SelectedLayer: {self.selectedLayer.dataProvider().dataSourceUri()} \n"
                # f"Image as array: {self.img}",
                ,level=Qgis.Success, duration=5)
